const actionTypes = Object.freeze({
    ADD_NOTE: 'ADD_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',
    GET_COFFEE_LIST: 'GET_COFFEE_LIST',
    GET_CART_LIST: 'GET_CART_LIST',
    CREATE_LINK_PAYMENT: 'CREATE_LINK_PAYMENT',
    GET_FAVOURITE_LIST: 'GET_FAVOURITE_LIST',
    IS_ITEM_FAVOUR: 'IS_ITEM_FAVOUR',
    CLEAR_PAYMENT_INFO: 'CLEAR_PAYMENT_INFO',
});
export default actionTypes;
